{% set name = "fastapi-cache2" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fastapi_cache2-{{ version }}.tar.gz
  sha256: 71bf4450117dc24224ec120be489dbe09e331143c9f74e75eb6f576b78926026

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - fastapi
    - uvicorn
    - typing_extensions >=4.1.0
    - importlib-metadata >=6.6.0,<7.0.0
    - pendulum >=3.0.0,<4.0.0
  run_constrained:
    - redis-py >=4.2.0-rc1,<5.0.0
    - aiomcache >=0.8.2,<0.9.0
    - aiobotocore >=2.13.1,<3.0.0

test:
  imports:
    - fastapi_cache
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/long2ice/fastapi-cache
  summary: Cache for FastAPI
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - zklaus
